# Generated by Django 4.1.4 on 2022-12-16 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='contrasena',
        ),
    ]
