# Generated by Django 4.1.4 on 2022-12-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_empleado_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='contrasena',
            field=models.CharField(default='1234', max_length=200),
        ),
    ]
